# required by readthedocs
# see https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
sphinx:
  configuration: Doc/conf.py

formats:
  - epub
  #- pdf

python:
  install:
    - requirements: Doc/requirements.txt
